env:
    global:
        - CC_TEST_REPORTER_ID=6c05d538a61c43d373a7d01a295ebb0f8e662f26e5fe2c629b2fce7b1bb7a929
language: node_js
node_js:
    - 13
    - 12
    - 10
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - yarn coverage:lcov
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
